[package]
name = "seedphrase_recovery"
version = "0.1.0"
authors = ["Zun"]
edition = "2021"

[dependencies]
bip39 = "2.0"
bitcoin = { version = "0.30", features = ["rand"] }
sha2 = "0.10"
secp256k1 = { version = "0.27", features = ["global-context", "rand-std"] }
colored = "2.0"
regex = "1.10"
cudarc = { version = "0.19", default-features = false, features = ["std", "driver", "nvrtc", "cuda-12000", "dynamic-loading"] }
ctrlc = "3"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
